# Generated by Django 3.1.3 on 2020-11-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ceated_date',
            new_name='create_date',
        ),
    ]
